version: '3'
services:
  backend:
    container_name: bookingsystem_backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DBUSER=postgres
      - DBPASSWORD=password
      - DBHOST=db
      - DBPORT=5432
      - DATABASENAME=booking_dev
    links:
      - db
    networks:
      - backend
  db:
      container_name: bookingsystem_db
      build: ./database
      ports:
        - "5018:5432"
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5018"]
          interval: 30s
          timeout: 10s
          retries: 5
      networks:
        - backend
networks:
  backend:
    driver: "bridge"