version: "2.4"
services:
  backend:
    container_name: booking_backend
    image: node:11
    volumes:
      - ./backend:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm run start:dev"
    environment:
      - DBHOST=db
    expose:
      - "3000"
    mem_limit: 4096M
  db:
    container_name: booking_db
    build: ./database
    expose:
      - "5432"
  frontend:
    container_name: booking_frontend
    image: node:11
    volumes:
      - ./frontend:/usr/src/frontend
    working_dir: /usr/src/frontend
    command: bash -c "npm install && npm rebuild node-sass && npm run serve"
    expose:
      - "8080"
  nginx-proxy:
    build: ./
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    container_name: nginx-proxy
